### ISSUE TITLE
[BUG] python bindings

### ISSUE THREAD

**Issue by niyatirawal** [MIT-SPARK/Hydra#59]
For installing the python package, when I do the last ``` pip install .``` , I get the following error. Any idea on how to fix it?
```       
      -- Build files have been written to: /home/lbaraldi/catkin_ws/src/hydra/build/temp.linux-x86_64-cpython-38
      [  1%] Building CXX object CMakeFiles/hydra.dir/src/backend/backend_module.cpp.o
      [  2%] Building CXX object CMakeFiles/hydra.dir/src/backend/backend_utilities.cpp.o
      [  3%] Building CXX object CMakeFiles/hydra.dir/src/backend/pgmo_configs.cpp.o
      [  4%] Building CXX object CMakeFiles/hydra.dir/src/backend/merge_tracker.cpp.o
      [  5%] Building CXX object CMakeFiles/hydra.dir/src/backend/surface_place_utilities.cpp.o
      [  6%] Building CXX object CMakeFiles/hydra.dir/src/backend/update_agents_functor.cpp.o
      [  7%] Building CXX object CMakeFiles/hydra.dir/src/backend/update_frontiers_functor.cpp.o
      [  8%] Building CXX object CMakeFiles/hydra.dir/src/backend/update_functions.cpp.o
      [  8%] Building CXX object CMakeFiles/hydra.dir/src/backend/update_objects_functor.cpp.o
      [  9%] Building CXX object CMakeFiles/hydra.dir/src/backend/update_places_functor.cpp.o
      [ 10%] Building CXX object CMakeFiles/hydra.dir/src/backend/update_rooms_buildings_functor.cpp.o
      [ 11%] Building CXX object CMakeFiles/hydra.dir/src/backend/update_surface_places_functor.cpp.o
      [ 12%] Building CXX object CMakeFiles/hydra.dir/src/common/batch_pipeline.cpp.o
      [ 13%] Building CXX object CMakeFiles/hydra.dir/src/common/config_utilities.cpp.o
      [ 14%] Building CXX object CMakeFiles/hydra.dir/src/common/global_info.cpp.o
      [ 15%] Building CXX object CMakeFiles/hydra.dir/src/common/hydra_pipeline.cpp.o
      [ 16%] Building CXX object CMakeFiles/hydra.dir/src/common/label_remapper.cpp.o
      [ 17%] Building CXX object CMakeFiles/hydra.dir/src/common/label_space_config.cpp.o
      [ 18%] Building CXX object CMakeFiles/hydra.dir/src/common/robot_prefix_config.cpp.o
      [ 19%] Building CXX object CMakeFiles/hydra.dir/src/common/semantic_color_map.cpp.o
      [ 20%] Building CXX object CMakeFiles/hydra.dir/src/common/shared_dsg_info.cpp.o
      [ 21%] Building CXX object CMakeFiles/hydra.dir/src/common/shared_module_state.cpp.o
      [ 22%] Building CXX object CMakeFiles/hydra.dir/src/frontend/frontend_module.cpp.o
      [ 23%] Building CXX object CMakeFiles/hydra.dir/src/frontend/gvd_place_extractor.cpp.o
      [ 24%] Building CXX object CMakeFiles/hydra.dir/src/frontend/frontier_extractor.cpp.o
      [ 25%] Building CXX object CMakeFiles/hydra.dir/src/frontend/mesh_segmenter.cpp.o
      c++: fatal error: Killed signal terminated program cc1plus
      compilation terminated.
      make[2]: *** [CMakeFiles/hydra.dir/build.make:412: CMakeFiles/hydra.dir/src/frontend/frontier_extractor.cpp.o] Error 1
      make[2]: *** Waiting for unfinished jobs....
      make[1]: *** [CMakeFiles/Makefile2:733: CMakeFiles/hydra.dir/all] Error 2
      make: *** [Makefile:136: all] Error 2
      /tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:215: _Warning: Package 'hydra_python.config.uhumans2' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'hydra_python.config.uhumans2' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'hydra_python.config.uhumans2' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'hydra_python.config.uhumans2' to be distributed and are
              already explicitly excluding 'hydra_python.config.uhumans2' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      Traceback (most recent call last):
        File "/home/lbaraldi/hydra_venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/lbaraldi/hydra_venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/lbaraldi/hydra_venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 102, in <module>
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-y55rxiga/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 77, in build_extension
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j4']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hydra_python
Failed to build hydra_python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (hydra_python) ```

**Comment by niyatirawal** [comment]
After following the instructions in the python bindings section and creating and sourcing a virtual environment, this error was fixed. I am currently facing an error when I try to execute `hydra habitat run /path/to/habitat/mp3d/17DRP5sb8fy/17DRP5sb8fy.glb`. The error is as follows:
`Traceback (most recent call last):
  File "/workspaces/catkin_ws/pyenv/bin/hydra", line 8, in <module>
    sys.exit(main.cli())
  File "/workspaces/catkin_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/workspaces/catkin_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/workspaces/catkin_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspaces/catkin_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspaces/catkin_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspaces/catkin_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
TypeError: run() missing 1 required positional argument: 'publish'`

**Comment by nathanhhughes** [comment]
Hi, thanks for your interest in our work! As you have seemed to have figured out, the build issue you encountered was gcc running out of memory. For future reference (if you haven't seen it yet), you can set the number of jobs that Hydra uses to compile the bindings by setting the `CMAKE_BUILD_PARELLEL_LEVEL` (see [here](https://github.mit.edu/SPARK/Hydra/blob/63f2585283fcaee4180c6d907fc10fb07a8d180a/setup.py#L65)). 

As per the error w.r.t. running the habitat command: sorry about that, it appears I didn't try that particular command before releasing. I pushed a fix to `main` that will at least fix that, but haven't had a chance to install and test the bindings fully.

**Comment by niyatirawal** [comment]
Many thanks for pushing the fix to main.  I wanted to extract scene graphs for the HM3D dataset. 
Upon executing: 
`hydra habitat run /workspaces/abc_ws/kfPV7w3FaU5.glb`, I now get the following error:
```
Renderer: NVIDIA GeForce GTX TITAN X/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 535.183.01
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_ES2_compatibility
    GL_ARB_separate_shader_objects
    GL_ARB_robustness
    GL_ARB_texture_storage
    GL_ARB_invalidate_subdata
    GL_ARB_texture_storage_multisample
    GL_ARB_multi_bind
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_texture_filter_anisotropic
    GL_KHR_debug
    GL_KHR_parallel_shader_compile
Using driver workarounds:
    no-forward-compatible-core-context
    nv-egl-incorrect-gl11-function-pointers
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
[15:05:30:151963]:[Sim] Simulator.cpp(240)::createSceneInstance : Navmesh file location in scene instance : 
[15:05:30:151992]:[Sim] Simulator.cpp(249)::createSceneInstance : Navmesh file not found, checked at filename : ''
[15:05:30:154204]:[Sim] Simulator.cpp(305)::createSceneInstance : Using scene instance-specified Light key : - no_lights -
[15:05:30:154249]:[Sim] Simulator.cpp(415)::instanceStageForSceneAttributes : Start to load stage named : /workspaces/abc_ws/kfPV7w3FaU5.glb with render asset : /workspaces/abc_ws/kfPV7w3FaU5.glb and collision asset : /workspaces/abc_ws/kfPV7w3FaU5.glb
[15:05:32:136250]:[Sim] Simulator.cpp(442)::instanceStageForSceneAttributes : Successfully loaded stage named : /workspaces/abc_ws/kfPV7w3FaU5.glb
[15:05:32:136302]:[Sim] Simulator.cpp(474)::instanceStageForSceneAttributes : 
---
The active scene does not contain semantic annotations : activeSemanticSceneID_ = 0  
---
[15:05:32:136362]:[Sim] Simulator.cpp(208)::reconfigure : CreateSceneInstance success == true for active scene name : /workspaces/abc_ws/kfPV7w3FaU5.glb  with renderer.
[15:05:32:235946]:[Sim] Simulator.cpp(898)::recomputeNavMesh : reconstruct navmesh successful
Traceback (most recent call last):
  File "/workspaces/abc_ws/pyenv/bin/hydra", line 8, in <module>
    sys.exit(main.cli())
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/hydra_python/commands/habitat.py", line 71, in run
    data = habitat.HabitatInterface(scene_path)
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/hydra_python/_plugins/habitat.py", line 201, in __init__
    self._make_instance_labelmap()
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/hydra_python/_plugins/habitat.py", line 231, in _make_instance_labelmap
    names = [name_mapping[ade_to_mpcat[idx]] for idx in keys]
  File "/workspaces/abc_ws/pyenv/lib/python3.8/site-packages/hydra_python/_plugins/habitat.py", line 231, in <listcomp>
    names = [name_mapping[ade_to_mpcat[idx]] for idx in keys]
KeyError: 0
[15:05:32:380711]:[Sim] Simulator.cpp(69)::~Simulator : Deconstructing Simulator
```

**Comment by niyatirawal** [comment]
For mp3d scene_dataset, I get `Segmentation fault (core dumped)`. There seems to be something wrong with the colors.
```
Renderer: NVIDIA GeForce GTX TITAN X/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 535.183.01
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_ES2_compatibility
    GL_ARB_separate_shader_objects
    GL_ARB_robustness
    GL_ARB_texture_storage
    GL_ARB_invalidate_subdata
    GL_ARB_texture_storage_multisample
    GL_ARB_multi_bind
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_texture_filter_anisotropic
    GL_KHR_debug
    GL_KHR_parallel_shader_compile
Using driver workarounds:
    no-forward-compatible-core-context
    nv-egl-incorrect-gl11-function-pointers
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
[09:55:43:220206]:[Sim] Simulator.cpp(240)::createSceneInstance : Navmesh file location in scene instance : /workspaces/abc_ws/data/versioned_data/mp3d_example_scene_1.1/17DRP5sb8fy/17DRP5sb8fy.navmesh
[09:55:43:220230]:[Sim] Simulator.cpp(245)::createSceneInstance : Loading navmesh from /workspaces/abc_ws/data/versioned_data/mp3d_example_scene_1.1/17DRP5sb8fy/17DRP5sb8fy.navmesh
[09:55:43:220313]:[Sim] Simulator.cpp(247)::createSceneInstance : Navmesh Loaded.
[09:55:43:245567]:[Sim] Simulator.cpp(305)::createSceneInstance : Using scene instance-specified Light key : - no_lights -
[09:55:43:245610]:[Sim] Simulator.cpp(415)::instanceStageForSceneAttributes : Start to load stage named : /workspaces/abc_ws/data/versioned_data/mp3d_example_scene_1.1/17DRP5sb8fy/17DRP5sb8fy.glb with render asset : /workspaces/abc_ws/data/versioned_data/mp3d_example_scene_1.1/17DRP5sb8fy/17DRP5sb8fy.glb and collision asset : /workspaces/abc_ws/data/versioned_data/mp3d_example_scene_1.1/17DRP5sb8fy/17DRP5sb8fy.glb
[09:55:47:269522]:[Sim] Simulator.cpp(442)::instanceStageForSceneAttributes : Successfully loaded stage named : /workspaces/abc_ws/data/versioned_data/mp3d_example_scene_1.1/17DRP5sb8fy/17DRP5sb8fy.glb
[09:55:47:269586]:[Sim] Simulator.cpp(208)::reconfigure : CreateSceneInstance success == true for active scene name : /workspaces/abc_ws/data/versioned_data/mp3d_example_scene_1.1/17DRP5sb8fy/17DRP5sb8fy.glb  with renderer.
[09:55:47:343102]:[Sim] Simulator.cpp(898)::recomputeNavMesh : reconstruct navmesh successful
[09:55:48:180817]:[Sim] Simulator.cpp(898)::recomputeNavMesh : reconstruct navmesh successful
Trajectory is 105.64831450406255 meters long
I0807 09:55:48.819205 35134 gvd_place_extractor.cpp:88] Downsampling TSDF when creating places!
I0807 09:55:48.845501 35134 hydra_pipeline.cpp:100] 
====================================================================================================
= Modules                                                                                          =
====================================================================================================

****************************************************************************************************
* backend                                                                                          *
****************************************************************************************************
========================================== BackendConfig ===========================================
visualize_place_factors:                     false
enable_rooms:                                true (default)
enable_buildings:                            true (default)
building_color:                              [169, "\b", �, �] (default)
building_semantic_label:                     22 (default)
use_2d_places:                               false (default)
add_places_to_deformation_graph:             true (default)
optimize_on_lc:                              true (default)
enable_node_merging:                         true (default)
merge_update_map:                            {BUILDINGS: false, OBJECTS: false, PLACES: true, ROOMS:
                                             false} (default)
merge_update_dynamic:                        true (default)
places_merge_pos_threshold_m:                0.3
places_merge_distance_tolerance_m:           0.2
use_mesh_subscribers:                        false (default)
enable_merge_undos:                          false (default)
use_active_flag_for_updates:                 true (default)
num_neighbors_to_find_for_merge:             1 (default)
zmq_send_url:                                tcp://127.0.0.1:8001 (default)
zmq_recv_url:                                tcp://127.0.0.1:8002 (default)
use_zmq_interface:                           false (default)
zmq_num_threads:                             2 (default)
zmq_poll_time_ms:                            10 (default)
zmq_send_mesh:                               true (default)
room_finder [RoomFinderConfig]:
   prefix:                                   R (default)
   min_dilation_m [m]:                       0.5
   max_dilation_m [m]:                       1.2
   min_window_size:                          0.2 (default)
   clip_dilation_window_to_max:              false (default)
   min_component_size:                       10
   min_room_size:                            10 (default)
   dilation_threshold_mode:                  PLATEAU
   min_lifetime_length_m:                    0.1 (default)
   plateau_ratio:                            0.25
   max_modularity_iters:                     5 (default)
   modularity_gamma:                         1 (default)
   clustering_mode:                          NEIGHBORS (default)
   dilation_diff_threshold_m [m]:            -1
   log_filtrations:                          false (default)
   log_place_graphs:                         false (default)
pgmo [HydraPgmoConfig]:
   run_mode:                                 FULL
   embed_trajectory_delta_t:                 5
   num_interp_pts:                           3
   interp_horizon:                           10
   add_initial_prior:                        true (default)
   output_prefix:                            "" (default)
   enable_sparsify:                          false (default)
   trans_node_dist:                          1 (default)
   rot_node_dist:                            1.2 (default)
   odom:                                     0.01
   loop_close:                               0.05
   prior:                                    0.01
   mesh_mesh:                                0.01
   pose_mesh:                                0.01
   odom_trans_threshold:                     0.05
   odom_rot_threshold:                       0.01
   pcm_trans_threshold:                      -1
   pcm_rot_threshold:                        -1
   gnc_alpha:                                0.9
   gnc_max_iterations:                       100 (default)
   gnc_mu_step:                              1.6
   gnc_cost_tolerance:                       1e-05 (default)
   gnc_weight_tolerance:                     0.0001 (default)
   gnc_fix_prev_inliers:                     true
   lm_diagonal_damping:                      true (default)
   place_mesh:                               0.01
   place_edge:                               0.01
   place_merge:                              10
   object_merge:                             10
   sg_loop_close:                            0.1
   gnc_fix_prev_inliers:                     true (default)
   verbosity:                                UPDATE (default)
   solver:                                   LM (default)
places2d_config [Places2dConfig] (default):
   allow_places_merge:                       true (default)
   merge_max_delta_z:                        0.5 (default)
   min_points:                               10 (default)
   min_size:                                 2 (default)
   connection_overlap_threshold:             0 (default)
   connection_max_delta_z:                   0.5 (default)
   connection_ellipse_scale_factor:          1 (default)
====================================================================================================
****************************************************************************************************

****************************************************************************************************
* frontend                                                                                         *
****************************************************************************************************
====================================== FrontendModule::Config ======================================
min_object_vertices:                         40
min_object_vertices:                         40
lcd_use_bow_vectors:                         true (default)
mesh_resolution:                             0.005
d_graph_resolution:                          2.5
time_horizon:                                15
use_frontiers:                               false (default)
objects [MeshSegmenterConfig] (default):
   prefix:                                   O (default)
   layer_id:                                 2 (default)
   active_index_horizon_m:                   7 (default)
   cluster_tolerance:                        0.25 (default)
   min_cluster_size:                         40 (default)
   max_cluster_size:                         100000 (default)
   bounding_box_type:                        AABB (default)
   timer_namespace:                          frontend/objects (default)
pose_graph_tracker [Virtual Config: PoseGraphFromOdom::Config]:
surface_places [Uninitialized Virtual Config]
freespace_places [Virtual Config: GvdPlaceExtractor::Config]:
   min_component_size:                       3 (default)
   filter_places:                            true (default)
   filter_ground:                            false (default)
   robot_height:                             0 (default)
   edge_tolerance:                           1 (default)
   node_tolerance:                           1 (default)
   add_freespace_edges:                      false (default)
   gvd [GvdIntegratorConfig]:
      max_distance_m:                        4.5
      min_distance_m:                        0.2 (default)
      min_diff_m:                            0.1
      min_weight:                            1e-06 (default)
      num_buckets:                           20 (default)
      multi_queue:                           false (default)
      refine_voxel_pos:                      false (default)
      positive_distance_only:                true (default)
      min_basis_for_extraction:              1
      voronoi_config [VoronoiCheckConfig]:
         mode:                               L1_THEN_ANGLE (default)
         min_distance_m:                     0.3
         parent_l1_separation:               20
         parent_cos_angle_separation:        0.2
   graph [Virtual Config: CompressionExtractorConfig]:
      node_merge_distance_m:                 0.5
      add_overlap_edges:                     false
      add_freespace_edges:                   true (default)
      compression_distance_m:                1
      validate_graph:                        false (default)
      min_node_distance_m:                   0.4
      min_edge_distance_m:                   0.2
      merge_new_nodes:                       true (default)
      add_heuristic_edges:                   true
      merge_policy:                          basis_points (default)
      freespace_edges [FreespaceEdgeConfig]:
         max_length_m:                       2 (default)
         num_nodes_to_check:                 10
         num_neighbors_to_find:              2
         min_clearance_m:                    0.2
   tsdf_interpolator [Virtual Config: DownsampleTsdfInterpolator::Config]:
      ratio:                                 2 (default)
      tolerance:                             1e-10 (default)
frontier_places [Uninitialized Virtual Config]
====================================================================================================
****************************************************************************************************

****************************************************************************************************
* reconstruction                                                                                   *
****************************************************************************************************

======================================= ReconstructionConfig =======================================
show_stats:                                  false
stats_verbosity:                             2 (default)
clear_distant_blocks:                        true (default)
dense_representation_radius_m:               8
num_poses_per_update:                        5
max_input_queue_size:                        0 (default)
semantic_measurement_probability:            0.9 (default)
tsdf [ProjectiveIntegrator]:
   verbosity:                                1
   use_weight_dropoff:                       true (default)
   weight_dropoff_epsilon [vs]:              -1 (default)
   use_constant_weight:                      false (default)
   max_weight:                               100000 (default)
   num_threads:                              8
   interpolation_method:                     bilinear
   semantic_integrator [Virtual Config: MLESemanticIntegrator::Config]:
      label_confidence:                      0.9 (default)
mesh [MeshIntegratorConfig]:
   min_weight:                               0.0001 (default)
   integrator_threads:                       8
robot_footprint [Uninitialized Virtual Config]
====================================================================================================
****************************************************************************************************
I0807 09:55:48.845571 35134 hydra_python_pipeline.cpp:117] ========================================== PipelineConfig ==========================================
enable_reconstruction:                       true (default)
enable_lcd:                                  false (default)
enable_places:                               true (default)
timing_disabled:                             false (default)
disable_timer_output:                        true (default)
enable_pgmo_logging:                         true (default)
default_verbosity:                           1 (default)
default_num_threads:                         -1 (default)
store_visualization_details:                 false (default)
label_names:                                 [{label: 0, name: void},
                                              {label: 1, name: wall},
                                              {label: 2, name: floor},
                                              {label: 3, name: chair},
                                              {label: 4, name: door},
                                              {label: 5, name: table},
                                              {label: 6, name: picture},
                                              {label: 7, name: cabinet},
                                              {label: 8, name: cushion},
                                              {label: 9, name: window},
                                              {label: 10, name: sofa},
                                              {label: 11, name: bed},
                                              {label: 12, name: curtain},
                                              {label: 13, name: chest_of_drawers},
                                              {label: 14, name: plant},
                                              {label: 15, name: sink},
                                              {label: 16, name: stairs},
                                              {label: 17, name: ceiling},
                                              {label: 18, name: toilet},
                                              {label: 19, name: stool},
                                              {label: 20, name: towel},
                                              {label: 21, name: mirror},
                                              {label: 22, name: tv_monitor},
                                              {label: 23, name: shower},
                                              {label: 24, name: column},
                                              {label: 25, name: bathtub},
                                              {label: 26, name: counter},
                                              {label: 27, name: fireplace},
                                              {label: 28, name: lighting},
                                              {label: 29, name: railing},
                                              {label: 30, name: shelving},
                                              {label: 31, name: blinds},
                                              {label: 32, name: seating},
                                              {label: 33, name: board_panel},
                                              {label: 34, name: furniture},
                                              {label: 35, name: appliances},
                                              {label: 36, name: clothes},
                                              {label: 37, name: objects},
                                              {label: 38, name: misc}]
room_colors:                                 [[166, �, �, �],
                                              [31, x, �, �],
                                              [178, �, �, �],
                                              [51, �, ",", �],
                                              [251, �, �, �],
                                              [227, "\x1a", "\x1c", �],
                                              [253, �, o, �],
                                              [255, "��", "\x00", �],
                                              [202, �, �, �],
                                              [106, =, �, �],
                                              [255, �, �, �],
                                              [177, Y, (, �]] (default)
reconstruction/map [VolumetricMap] (default):
   voxel_size [m]:                           0.1 (default)
   voxels_per_side:                          16 (default)
   truncation_distance [m]:                  0.3 (default)
logs [LogConfig] (default):
   log_path:                                 "" (default)
   log_timing_incrementally:                 false (default)
   timing_stats_name:                        timing_stats.csv (default)
   timing_suffix:                            _timing_raw.csv (default)
   log_raw_timers_to_single_dir:             false (default)
frames [FrameConfig] (default):
   robot_frame:                              base_link (default)
   odom_frame:                               odom (default)
   map_frame:                                map (default)
label_space [LabelSpaceConfig]:
   total_semantic_labels:                    39
   semantic_colormap_file:                   "" (default)
   semantic_label_remap_filepath:            "" (default)
   dynamic_labels:                           [] (default)
   invalid_labels:                           [0]
   object_labels:                            [3, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 18, 19, 20, 21,
                                             22, 23, 25, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37]
   surface_places_labels:                    [2, 16]
====================================================================================================
*** Aborted at 1723024548 (unix time) try "date -d @1723024548" if you are using GNU date ***
PC: @     0x7fce6d39b623 flann::anyimpl::small_any_policy<>::print()
*** SIGSEGV (@0x9) received by PID 35134 (TID 0x7fce3eefe700) from PID 9; stack trace: ***
    @     0x7fce65478631 (unknown)
    @     0x7fce9eeb7090 (unknown)
    @     0x7fce6d39b623 flann::anyimpl::small_any_policy<>::print()
    @     0x7fce65fee6ad flann::get_param<>()
    @     0x7fce66037642 pcl::KdTreeFLANN<>::setInputCloud()
    @     0x7fce660323aa pcl::search::KdTree<>::setInputCloud()
    @     0x7fce6602e818 hydra::findClusters()
    @     0x7fce6602ef9d hydra::MeshSegmenter::detect()
    @     0x7fce65face6a hydra::FrontendModule::updateObjects()
    @     0x7fce89846df4 (unknown)
    @     0x7fce9ee59609 start_thread
    @     0x7fce9ef93353 clone
Segmentation fault (core dumped)
```
